### ISSUE TITLE
Question...

### ISSUE THREAD

**Issue by chemitaxis** [itteco/redactor-oembed#3]
Hi! I'm using this amazing plugin... but I don't know whay is these files:

<link rel="stylesheet" href="iframely.css" />

<script src="iframely.js"></script>

Where I download it? I have whatched the code of index.html.

If a put this code with my API Key, I have an error, why?
// Setup your iframely endpoint path. The sample is given for cloud version
$.iframely.defaults.endpoint = 'http://iframe.ly/api/oembed?api_key={YOUR API KEY HERE}';

I have the error that $.iframely is undefined...

I have the plugin working... but I don't know what API Key is using... 

Regards!!

**Comment by nleush** [comment]
Hi!

Thanks for your feedback. Looks like docs was from older version. Plugin was working using demo api endpoint.

Code and README file was just updated to fix that.

Please, look here for working example: https://github.com/itteco/redactor-oembed#sample--config and respond if it works for you.

Regards!

**Comment by iparamonau** [comment]
I trust this should be resolved now
